version: '3.7'
services:
      
  api_rest:
    container_name: dnd_docker
    build: .
    ports: 
      - 5000:5000
    restart: always
    x-develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json